{% set name = "inquirerpy" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/InquirerPy-{{ version }}.tar.gz
  sha256: 89d2ada0111f337483cb41ae31073108b2ec1e618a49d7110b0d7ade89fc197e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<4.0
    - pfzy >=0.3.1,<0.4.0
    - prompt-toolkit >=3.0.1,<4.0.0

test:
  imports:
    - InquirerPy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kazhala/InquirerPy
  summary: Python port of Inquirer.js (A collection of common interactive command-line user interfaces)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - avsthiago
